title: LINK Dataset
description: Long-term intracortical neural activity and kinematics (Chestek Lab)
theme: jekyll-theme-cayman
markdown: kramdown

# Top navigation
header_pages:
  - index.md
  - data.md
